"""added visit date to module

Revision ID: 19dfa70ef473
Revises: e7d3637ee4f4
Create Date: 2020-11-04 10:32:55.775213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dfa70ef473'
down_revision = 'e7d3637ee4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('visit_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'visit_date')
    # ### end Alembic commands ###
