"""fix previous one to one

Revision ID: 226e9a4fe9a5
Revises: 4c454ddff544
Create Date: 2020-10-31 01:19:45.561715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226e9a4fe9a5'
down_revision = '4c454ddff544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
