"""added one to one project/config

Revision ID: 4c454ddff544
Revises: 90fec98b3b2a
Create Date: 2020-10-31 01:18:45.473031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c454ddff544'
down_revision = '90fec98b3b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'config', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'config', type_='foreignkey')
    op.drop_column('config', 'project_id')
    # ### end Alembic commands ###
