"""added fast mode

Revision ID: 572c1845132c
Revises: 7a8ec57242a4
Create Date: 2020-11-07 18:11:53.068601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572c1845132c'
down_revision = '7a8ec57242a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('fast', sa.Boolean(), nullable=True))
    op.add_column('module', sa.Column('external', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'external')
    op.drop_column('config', 'fast')
    # ### end Alembic commands ###
