"""added special project for external lib

Revision ID: 7a8ec57242a4
Revises: db95fa6a3f22
Create Date: 2020-11-04 16:37:22.325414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8ec57242a4'
down_revision = 'db95fa6a3f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('onedir', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'onedir')
    # ### end Alembic commands ###
