"""added path column to project

Revision ID: 8351a546abd9
Revises: 8d4bf55cb4c0
Create Date: 2020-10-31 01:10:22.187370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8351a546abd9'
down_revision = '8d4bf55cb4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'path')
    # ### end Alembic commands ###
