"""added scope table

Revision ID: a097ceff5c00
Revises: 5faf0c7695f5
Create Date: 2020-10-31 01:48:38.915962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a097ceff5c00'
down_revision = '5faf0c7695f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indent_level', sa.Integer(), nullable=True),
    sa.Column('indent_level_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('variable', sa.Column('scope_id', sa.Integer(), nullable=True))
    op.drop_constraint('variable_ibfk_1', 'variable', type_='foreignkey')
    op.create_foreign_key(None, 'variable', 'scope', ['scope_id'], ['id'])
    op.drop_column('variable', 'module_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('module_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'variable', type_='foreignkey')
    op.create_foreign_key('variable_ibfk_1', 'variable', 'module', ['module_id'], ['id'])
    op.drop_column('variable', 'scope_id')
    op.drop_table('scope')
    # ### end Alembic commands ###
