"""added col and line number to variable

Revision ID: d34395018755
Revises: 19dfa70ef473
Create Date: 2020-11-04 10:44:43.026004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34395018755'
down_revision = '19dfa70ef473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('colno', sa.Integer(), nullable=True))
    op.add_column('variable', sa.Column('first_definition', sa.Boolean(), nullable=True))
    op.add_column('variable', sa.Column('lineno', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variable', 'lineno')
    op.drop_column('variable', 'first_definition')
    op.drop_column('variable', 'colno')
    # ### end Alembic commands ###
