"""updated config and project tables

Revision ID: db95fa6a3f22
Revises: 214b12ad3201
Create Date: 2020-11-04 13:18:27.926946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db95fa6a3f22'
down_revision = '214b12ad3201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('external', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'version')
    op.drop_column('project', 'external')
    # ### end Alembic commands ###
