"""added import table

Revision ID: e7d3637ee4f4
Revises: 0132963aa383
Create Date: 2020-10-31 17:59:14.259923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d3637ee4f4'
down_revision = '0132963aa383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('asname', sa.String(length=50), nullable=True),
    sa.Column('module_from_id', sa.Integer(), nullable=True),
    sa.Column('module_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_from_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['module_to_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import')
    # ### end Alembic commands ###
